# Generated by Django 2.0.9 on 2020-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified at')),
                ('product_name', models.CharField(max_length=140, verbose_name='product name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=255, verbose_name='product description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='products/pictures')),
                ('product_sell', models.PositiveIntegerField(default=0)),
                ('product_stock', models.PositiveIntegerField(default=0)),
                ('product_attribute', models.CharField(max_length=210, verbose_name='product atttibute')),
                ('is_public', models.BooleanField(default=True, help_text='If this product should sell')),
            ],
            options={
                'ordering': ['-product_sell', '-product_stock'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
